version: "3.7"

networks:
  api-network:
    name: api-network
#    external: true
  api-proxy.network:
    name: api-proxy.network
#    external: true

services:
  api-app:
    container_name: api-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - api-mysql
      - api-redis
    env_file:
      - .env
    volumes:
      - ./:/app:cached
    extra_hosts:
      - "host.docker.internal:host-gateway" #for xDebug
    networks:
      - api-network

  api-app-nginx:
    container_name: api-app-nginx
    build:
      context: ./docker/nginx
    depends_on:
      - api-app
    volumes:
      - ./public:/app/public:cached
    networks:
      - api-network
      - api-proxy.network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-nginx.rule=Host(`api.localhost`)

  api-redis:
    container_name: api-redis
    build:
      context: ./docker/redis
    command: redis-server --appendonly yes
    hostname: "redis"
    volumes:
      - api-redis-storage:/data
    networks:
      - api-network
      - api-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.api-redis.loadBalancer.server.port=6379
      - traefik.tcp.routers.api-redis.entrypoints=redis
      - traefik.tcp.routers.api-redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.api-redis.service=api-redis

  api-mysql:
    container_name: api-mysql
    build:
      context: ./docker/mysql
    volumes:
      - api-mysql-storage:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - api-network
      - api-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.api-mysql.loadBalancer.server.port=3306
      - traefik.tcp.routers.api-mysql.entrypoints=mysql
      - traefik.tcp.routers.api-mysql.rule=HostSNI(`*`)
      - traefik.tcp.routers.api-mysql.service=api-mysql

  api-rabbit:
    container_name: api-rabbit
    build:
      context: ./docker/rmq
    volumes:
      - api-rabbit-storage:/var/lib/rabbitmq
    networks:
      - api-network
      - api-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.api-rabbit.loadBalancer.server.port=5672
      - traefik.tcp.routers.api-rabbit.entrypoints=rabbit
      - traefik.tcp.routers.api-rabbit.rule=HostSNI(`*`)
      - traefik.tcp.routers.api-rabbit.service=api-rabbit

  api-proxy:
    container_name: api-proxy
    image: traefik:v2.5
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=api-proxy.network
      - --providers.docker.useBindPortIP=false
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:6379
      - --entrypoints.mysql.address=:3306
      - --entrypoints.rabbit.address=:5672
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "6379:6379"
      - "3306:3306"
      - "5672:5672"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - api-proxy.network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api-proxy.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

volumes:
  api-redis-storage:
  api-mysql-storage:
  api-rabbit-storage:
