POST http://api.localhost/api/users
Accept: application/json
Content-type: application/json

{
    "users": [
        {
            "username": "000com",
            "email": "olenadodon000@gmail.com",
            "country_code": "UA"
        },
        {
            "username": "nsssse",
            "email": "test@gmail.com",
            "country_code": "BV"
        }
    ]
}

###
PUT http://api.localhost/api/users
Accept: application/json
Content-type: application/json

{
    "users": [
        {
            "username": "000111com",
            "email": "olenadodon000@gmail.com",
            "country_code": "UA"
        },
        {
            "username": "nsssse",
            "email": "test@gmail.com",
            "country_code": "WF"
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
DELETE http://api.localhost/api/users
Accept: application/json
Content-type: application/json

{
    "users": [
        {
            "username": "000111com",
            "email": "olenadodon000@gmail.com",
            "country_code": "UA"
        },
        {
            "username": "nsssse",
            "email": "test@gmail.com",
            "country_code": "WF"
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}


###
GET http://api.localhost/api/users
Accept: application/json
Content-type: application/json

###
POST http://api.localhost/api/labels
Accept: application/json
Content-type: application/json

{
    "labels": [
        {
            "name": "label5f"
        },
        {
            "name": "label66"
        },
        {
            "name": "label88"
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
PUT http://api.localhost/api/link-labels
Accept: application/json
Content-type: application/json

{
    "labels": [
        {
            "name": "label5f",
            "projects": [
                {
                    "name": "project2"
                },
                {
                    "name": "project9"
                }
            ]
        },
        {
            "name": "label88",
            "projects": [
                {
                    "name": "project7"
                }
            ]
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
DELETE http://api.localhost/api/labels
Accept: application/json
Content-type: application/json

{
    "labels": [
        {
            "name": "label5f"
        },
        {
            "name": "label66"
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
GET http://api.localhost/api/labels
Accept: application/json
Content-type: application/json

{
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
POST http://api.localhost/api/projects
Accept: application/json
Content-type: application/json

{
    "projects": [
        {
            "name": "project99",
            "members": [
                {
                    "email": "olenadodon000@gmail.com"
                }
            ],
            "labels": [
                {
                    "name": "label1"
                },
                {
                    "name": "label4"
                }
            ]
        },
        {
            "name": "project999",
            "members": [
                {
                    "email": "olenadodon000@gmail.com"
                }
            ],
            "labels": [
                {
                    "name": "label1"
                },
                {
                    "name": "label4"
                }
            ]
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
PUT http://api.localhost/api/projects
Accept: application/json
Content-type: application/json

{
    "projects": [
        {
            "name": "project99",
            "members": [
                {
                    "email": "olenadodon000@gmail.com"
                }
            ],
            "labels": [
                {
                    "name": "label5"
                },
                {
                    "name": "label4"
                }
            ]
        },
        {
            "name": "project999",
            "members": [
                {
                    "email": "olenadodon000@gmail.com"
                }
            ],
            "labels": [
                {
                    "name": "label5"
                },
                {
                    "name": "label4"
                }
            ]
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
DELETE http://api.localhost/api/projects
Accept: application/json
Content-type: application/json

{
    "projects": [
        {
            "name": "project99"
        },
        {
            "name": "project999"
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
PUT http://api.localhost/api/link-projects
Accept: application/json
Content-type: application/json

{
    "projects": [
        {
            "name": "project2",
            "users": [
                {
                    "email": "test@gmail.com"
                }
            ]
        },
        {
            "name": "project7",
            "users": [
                {
                    "email": "test@gmail.com"
                }
            ]
        }
    ],
    "email": "olenadodon000@gmail.com",
    "token": ""
}

###
GET http://api.localhost/api/projects
Accept: application/json
Content-type: application/json

{
    "email": "olenadodon000@gmail.com",
    "token": ""
}



